#!/bin/sh

# Adapted from https://github.com/lamps-wg/dilithium-certificates/blob/main/examples/pretty

for param in id-MLDSA65-ECDSA-P256-SHA512
do
    for type in signed-attrs #no-signed-attrs
    do
        variant="$param-$type"
        ~/go/bin/der2ascii -pem -i $variant.pem -o $variant.tmp
        fold -w 64 $variant.tmp > $variant.txt
        rm $variant.tmp
    done
done